tap "airbytehq/tap"
tap "anomalyco/tap"
tap "aquasecurity/trivy"
tap "buo/cask-upgrade"
tap "chainguard-dev/tap"
tap "ruimarinho/tap"
tap "trufflesecurity/trufflehog"
tap "wagoodman/dive"
tap "withgraphite/tap"

# Editors
cask "visual-studio-code"
# cask "sublime-text"
# cask "pycharm"
brew "vim"

# Terminal
cask "iterm2"

# Shell
brew "fish"

# Languages
brew "ruby"
# brew "node"
brew "go"
brew "nvm"
brew "uv"
brew "virtualenv"
brew "protobuf"
# brew "python3"
# brew "pyenv"
# brew "pyenv-virtualenv"
# brew "yarn"

# Tools
brew "curl"
brew "wget"
brew "ack"
brew "cloc"
brew "ripgrep"
brew "git"
brew "git-gui"
brew "git-flow"
brew "git-filter-repo"
brew "p7zip"
brew "pre-commit"
brew "jq"
brew "tmux"
brew "eza"
brew "openssh"
brew "gh"
brew "anomalyco/tap/opencode"
# brew "coreutils"
# brew "dive"
# cask "vlc"
# cask "meld"
# cask "p4v"
# cask "flux"
# cask "rar"

# Docker
cask "docker-desktop"
# brew "helm"
# brew "devspace"

# Browsers
brew "lynx"
cask "firefox"
cask "brave-browser"
# cask "google-chrome"
# cask "torbrowser"

# Cloud CLI
cask "gcloud-cli"
brew "awscli"
# brew "aws-iam-authenticator"
# brew "firebase-cli"
# brew "gsts"
# brew "newman"

# Security Scanner
brew "trivy"

# Database
# brew "postgresql@14"
# brew "rethinkdb"
# brew "mongodb"
# brew "mysql"
# cask "dbeaver-community"

# Optional
cask "slack"
# cask "lastpass"
# cask "zoom"
# cask "loom"
# cask "obsidian"

# VSCode Extensions
vscode "42crunch.vscode-openapi"
vscode "amazonwebservices.aws-toolkit-vscode"
vscode "atlassian.atlascode"
vscode "bmalehorn.shell-syntax"
vscode "charliermarsh.ruff"
vscode "dbaeumer.vscode-eslint"
vscode "docker.docker"
vscode "eamodio.gitlens"
vscode "editorconfig.editorconfig"
vscode "git-ai.git-ai-vscode"
vscode "github.copilot-chat"
vscode "github.vscode-github-actions"
vscode "hashicorp.terraform"
vscode "jakebecker.elixir-ls"
vscode "mechatroner.rainbow-csv"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode.makefile-tools"
vscode "ms-vsliveshare.vsliveshare"
vscode "njpwerner.autodocstring"
vscode "randomfractalsinc.vscode-data-preview"
vscode "redhat.java"
vscode "redhat.vscode-yaml"
vscode "samuelcolvin.jinjahtml"
vscode "skyapps.fish-vscode"
vscode "tamasfe.even-better-toml"
vscode "tht13.rst-vscode"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "vscjava.migrate-java-to-azure"
vscode "vscjava.vscode-gradle"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-java-dependency"
vscode "vscjava.vscode-java-pack"
vscode "vscjava.vscode-java-test"
vscode "vscjava.vscode-java-upgrade"
vscode "vscjava.vscode-maven"
vscode "vscode-icons-team.vscode-icons"

# Go packages
go "github.com/google/gnostic"
go "github.com/googleapis/gnostic-grpc"
go "github.com/golang/protobuf/protoc-gen-go"
